version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: echo "hello world" > /tmp/output.txt
      - persist_to_workspace:
            root: /tmp/
            paths:
              - output.txt
        
  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          command: cat /tmp/output.txt
  print_job:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id:
          to: "printer"



commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << echo $CIRCLE_WORKFLOW_ID >>
 

workflows:
  storage_task:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - print_job
