version: 2.1

jobs:
  obi:
    docker:
      - image:  circleci/node:13.8.0
    steps:
      - run: ech "hello_world"
      - run: 
          echo "This is a success"
          when: on_fail


workflows:
  test:
    jobs:
      - obi
