version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: echo "hello world" > /tmp/output.txt
      - persist_to_workspace:
            root: /tmp/
            paths:
              - output.txt
        
  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          command: cat /tmp/output.txt

workflows:
  storage_task:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
